export interface Product {
  id?: number;
  code?: string; //@Ghislain please what is the rule of this variable??
  //@Ghislain is it the user entring the code or it will be generated by the application
   name?: string;
  description?: string;
  price?: number;
  quantity?: number;
  inventoryStatus?: string;
  category?: string;
  image?: string;
  rating?: number;
  createdDate?: Date;
  publishedDate?: string;
  title?: string;
  imageUrl?: string;
  heart?: boolean;
  content?: string;
  updatedDate?: string;
  summary?: string;
}
