export interface Product {
  id?: number;
  code?: string; // please what is the rule of this variable??
  // is it the user entring the code or it will be generated by the application
  // @idrice: that question is for you or for me??
  name?: string;
  description?: string;
  price?: number;
  quantity?: number;
  inventoryStatus?: string;
  category?: string;
  image?: string;
  rating?: number;
  createdDate?: string;
  publishedDate?: string;
  title?: string;
  imageUrl?: string;
  heart?: boolean;
  content?: string;
  updatedDate?: string;
  summary?: string;
}
