name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # https://github.com/mathieudutour/github-tag-action#readme
      - name: Bump Version and Push tag
        id: GhislainAndIdrice_Tag
        uses: mathieudutour/github-tag-action@v5.5 # Calling specified Action mathieu..
        with: # Passing parameter to action
          github_token: ${{ secrets.GITHUB_TOKEN }}

        # No 'uses' keyword because we want to run script from package.json file
      - name: Deployment in Action
        run: |
          npm i
          npm run deploy

      # https://github.com/ncipollo/release-action/blob/main/README.md
      - name: Generate File for Webpage # TODO What happen here ?
        uses: ncipollo/release-action@v1
        with:
          artifacts: "docs/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.GhislainAndIdrice_Tag.outputs.new_tag}} # using value of an action mathieu..
          replacesArtifacts: true
